#!/bin/sh

# 1. 稍微延时 2 秒，确保系统的网络和其他基础组件已初始化完毕
sleep 2

# 2. 检查系统中是否真的存在 ttyd 配置（防报错机制，-q 表示静默执行）
if uci -q get ttyd.@ttyd[0] > /dev/null; then
    # 强行覆盖配置
    uci -q set ttyd.@ttyd[0].command='/bin/login -f root'
    uci -q set ttyd.@ttyd[0].login='0'
    uci commit ttyd
    
    # 重启服务使之生效
    /etc/init.d/ttyd restart
fi

# 3. 这里的 exit 0 非常关键！OpenWrt 检测到执行成功（返回 0），就会在开机后自动删除这个脚本。保证它只在刷机后的第一次开机运行，绝不残留垃圾。
exit 0
